---
- name: Install OpenStack packages on Ubuntu
  package:
    name: "{{ item }}"
    state: present
  loop:
    - nova-api
    - nova-conductor
    - nova-novncproxy
    - nova-scheduler
    - neutron-server
    - neutron-linuxbridge-agent
    - neutron-dhcp-agent
    - neutron-metadata-agent
    - keystone
    - glance-api
    - cinder-api
    - cinder-scheduler
    - cinder-volume
    - heat-api
    - heat-api-cfn
    - heat-engine
  when: "ansible_os_family == 'Debian'"

- name: Install OpenStack packages on CentOS
  package:
    name: "{{ item }}"
    state: present
  loop:
    - centos-release-openstack-victoria
    - centos-release-openstack-ussuri
    - centos-release-openstack-train
    - centos-release-openstack-stein
    - centos-release-openstack-rocky
    - centos-release-openstack-queens
    - centos-release-openstack-pike
  when: "ansible_os_family == 'RedHat'"
